import { DeletIcon } from "./Icons";

export const shopCategories = [
  {
    title: "Vegetarian and vegan products",
    img: "/assets/images/shop-img-1.png",
    color: "#F2EBD9",
  },
  {
    title: "Vegetables and fruits for a balanced diet ",
    img: "/assets/images/shop-img-2.png",
    color: "#F4EAEA",
  },
  {
    title: "Delicious energy for every day",
    img: "/assets/images/shop-img-3.png",
    color: "#E9ECF4",
  },
];

export const hotpromotionsdata = [
  {
    imageURL: "/assets/images/timercard.png",
  },
  {
    imageURL: "/assets/images/timercar2.png",
  },
  {
    imageURL: "/assets/images/timercard.png",
  },
];
export const shopCatData = [
  {
    link: "/catalog",
    name: "Sets",
    img: "/assets/images/Sets.png",
    color: "bg-[#F2F0F0]",
  },
  {
    link: "/catalog",
    name: "Fruits",
    img: "/assets/images/Fruits.png",
    color: "bg-[#E9ECF4]",
  },
  {
    link: "/catalog",
    name: "Vegetables",
    img: "/assets/images/Vegetables.png",
    color: "bg-[#F4EAEA]",
  },
  {
    link: "/catalog",
    name: "Greenery",
    img: "/assets/images/Greenery.png",
    color: "bg-[#FD7777]",
  },
  {
    link: "/catalog",
    name: "/Fungi",
    img: "/assets/images/Fungi.png",
    color: "bg-[#F2EBD9]",
  },
  {
    link: "/catalog",
    name: "Groceries",
    img: "/assets/images/Groceries.png",
    color: " bg-[#F4EAEA]",
  },
  {
    link: "/catalog",
    name: "Sweets",
    img: "/assets/images/Sweets.png",
    color: "bg-[#F2F0F0]",
  },
  {
    link: "/catalog",
    name: "Drinks",
    img: "/assets/images/Drinks.png",
    color: "bg-[#E9ECF4]",
  },
  {
    link: "/catalog",
    name: "Sets",
    img: "/assets/images/Sets.png",
    color: "bg-[#F2F0F0]",
  },
];
export const vegetablesCategories = [
  {
    title: "Vegetarian and vegan products",
    img: "/assets/images/painapple.png",
    color: "#FFFFFF",
  },
  {
    title: "Vegetables and fruits for a balanced diet ",
    img: "/assets/images/banana.png",
    color: "#FFFFFF",
  },
  {
    title: "Delicious energy for every day",
    img: "/assets/images/grappees.png",
    color: "#FFFFFF",
  },
];
export const popularProducts = [
  {
    banertype: "Sale",
    title: "5 Star Dhara",
    productimg: "/assets/images/5star1.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: 5,
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#67BCEE]",
    liked: false,
  },
  {
    banertype: "New",
    title: "Ground allspice",
    productimg: "/assets/images/5star2.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#27CA7D]",
    liked: true,
  },
  {
    banertype: " ",
    title: "Wash the carrot",
    productimg: "/assets/images/5star3.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[]",
    liked: true,
  },
  {
    banertype: "Hote",
    title: "Boston",
    productimg: "/assets/images/5star4.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#F74B81]",
    liked: true,
  },
  {
    banertype: " ",
    title: "Petya Zhovta",
    productimg: "/assets/images/5star5.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[]",
    liked: true,
  },
  {
    banertype: "Hote",
    title: "Boby Edamame c/m",
    productimg: "/assets/images/5star6.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#F74B81]",
    liked: true,
  },
  {
    banertype: "Sale",
    title: "Kiwi Gold",
    productimg: "/assets/images/5star7.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#67BCEE]",
    liked: false,
  },
  {
    banertype: "New",
    title: "Mushroom Shiitake",
    productimg: "/assets/images/5star8.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#27CA7D]",
    liked: true,
  },
  {
    banertype: "New",
    title: "Mushroom Shiitake",
    productimg: "/assets/images/5star9.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#27CA7D]",
    liked: true,
  },
  {
    banertype: "New",
    title: "Mushroom Shiitake",
    productimg: "/assets/images/5star10.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#27CA7D]",
    liked: true,
  },
];

export const productsWithDeliverylist = [
  {
    title: "Berries",
  },
  {
    title: "Greens and salads",
  },
  {
    title: "Dried fruits",
  },
  {
    title: "Spices",
  },
  {
    title: "Flour and cereals",
  },
  {
    title: "Vegetables",
  },
];
export const productsWithDeliverydesc = [
  {
    title:
      "Another highlight of Nolorn is the opportunity to buy exotic fruits. Our assortment includes more than 500 exotic fruits from different parts of the world. It is difficult to buy them in a regular supermarket. However, using our delivery, you can easily feel the exotic taste.",
  },
  {
    title:
      "Looking for an original gift for a loved one, friend or colleague? In our online grocery store you can order Fruit Box - a set of exotic fruits in a beautiful craft box. Such a gift will be remembered for a long time and will cause pleasant emotions and impressions of new tastes. In addition, you can assemble and buy such a set yourself by choosing any fruits, berries or nuts from the assortment.",
  },
  {
    title:
      "The high quality of our products is confirmed by relevant certificates and the international HACCP certificate. We make sure that customers receive only selected natural products, ready to use. They are stored in our own warehouses where the correct temperature is maintained to keep them fresh and ripe.",
  },
];
export const topSellingsdata = [
  {
    img: "/assets/images/selling-img-3.png",
    title: "Product name",
    text: "Additional text",
    price: "$24.00  ",
    delPrice: "$30.00",
  },
  {
    img: "/assets/images/selling-img-2.png",
    title: "Product name",
    text: "Additional text",
    price: "$24.00  ",
    delPrice: "$30.00",
  },
  {
    img: "/assets/images/selling-img-1.png",
    title: "Product name",
    text: "Additional text",
    price: "$24.00  ",
    delPrice: "$30.00",
  },
];

export const latestpostsdata = [
  {
    img: "/assets/images/ginger-rice-bowls-image.png",
    title: "Sticky Ginger Rice Bowls",
    date: "June 22, 2022",
  },
  {
    img: "/assets/images/ginger-rice-bowls-image.png",
    title: "Sticky Ginger Rice Bowls",
    date: "June 22, 2022",
  },
  {
    img: "/assets/images/ginger-rice-bowls-image.png",
    title: "Sticky Ginger Rice Bowls",
    date: "June 22, 2022",
  },
];

export const tabledata = [
  {
    img: "/assets/images/table1.png",
    title: "Garbuz Ukraine",
    category: "Vegetables ",
    weight: "1 kg",
    price: "$24.00",
    delPrice: "$30.00",
    deletIcon: <DeletIcon />,
  },
  {
    img: "/assets/images/table2.png",
    title: "Garbuz Ukraine",
    category: "Vegetables ",
    weight: "1 kg",
    price: "$24.00",
    delPrice: "$30.00",
    deletIcon: <DeletIcon />,
  },
  {
    img: "/assets/images/table3.png",
    title: "Garbuz Ukraine",
    category: "Vegetables ",
    weight: "1 kg",
    price: "$24.00",
    delPrice: "$30.00",
    deletIcon: <DeletIcon />,
  },
];
export const fruitsProducts = [
  {
    title: "This is a great remedy for those who suffer from constipation.",
  },
  {
    title: "Figs can increase hemoglobin if eaten regularly.",
  },
  {
    title:
      "Elimination of toxins and normalization of digestion leads to weight loss.",
  },
];

export const catalogproductsdata = [
  {
    banertype: "Sale",
    title: "Garbuz Ukraine",
    productimg: "/assets/images/popular-img-1.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#67BCEE]",
    liked: false,
  },
  {
    banertype: "New",
    title: "Ground allspice",
    productimg: "/assets/images/Picture.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#27CA7D]",
    liked: true,
  },
  {
    banertype: "",
    title: "Wash the carrot",
    productimg: "/assets/images/Picture (1).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[]",
    liked: true,
  },
  {
    banertype: "Hote",
    title: "Boston",
    productimg: "/assets/images/Picture (2).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#F74B81]",
    liked: true,
  },
  {
    banertype: " ",
    title: "Petya Zhovta",
    productimg: "/assets/images/Picture (3).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[]",
    liked: true,
  },
  {
    banertype: "Hote",
    title: "Boby Edamame c/m",
    productimg: "/assets/images/Picture (4).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#F74B81]",
    liked: true,
  },
  {
    banertype: "Sale",
    title: "Kiwi Gold",
    productimg: "/assets/images/Picture (5).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#67BCEE]",
    liked: false,
  },
  {
    banertype: "New",
    title: "Mushroom Shiitake",
    productimg: "/assets/images/Picture (6).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#27CA7D]",
    liked: true,
  },
  {
    banertype: "Sale",
    title: "Garbuz Ukraine",
    productimg: "/assets/images/popular-img-1.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#67BCEE]",
    liked: false,
  },
  {
    banertype: "New",
    title: "Ground allspice",
    productimg: "/assets/images/Picture.png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#27CA7D]",
    liked: true,
  },
  {
    banertype: " ",
    title: "Wash the carrot",
    productimg: "/assets/images/Picture (1).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[]",
    liked: true,
  },
  {
    banertype: "Hote",
    title: "Boston",
    productimg: "/assets/images/Picture (2).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#F74B81]",
    liked: true,
  },
  {
    banertype: " ",
    title: "Petya Zhovta",
    productimg: "/assets/images/Picture (3).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[]",
    liked: true,
  },
  {
    banertype: "Hote",
    title: "Boby Edamame c/m",
    productimg: "/assets/images/Picture (4).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#F74B81]",
    liked: true,
  },
  {
    banertype: "Sale",
    title: "Kiwi Gold",
    productimg: "/assets/images/Picture (5).png",
    ratingimg: "/assets/images/rating.png",
    ratingvalue: "4",
    bannercolor: "#F2EBD9",
    quantitycheck: "Price per kg",
    oldPrice: "$30.00",
    newPrice: "$24.00",
    color: "bg-[#67BCEE]",
    liked: false,
  },
];
export const reviewsdata = [
  {
    img: "/assets/images/reviews-img-user.png",
    name: "Marina",
    time: "December 4, 2022 at 3:12 pm",
    desc: "“They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.” “They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.”",
  },
  {
    img: "/assets/images/reviews-img-user.png",
    name: "Marina",
    time: "December 4, 2022 at 3:12 pm",
    desc: "“They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.” “They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.”",
  },
  {
    img: "/assets/images/reviews-img-user.png",
    name: "Misha",
    time: "December 4, 2022 at 3:12 pm",
    desc: "“They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.” “They keep you informed throughout and make sure that you get the loan to suit your individual needs. Don't waste your time going anywhere else.”",
  },
];
export const faqData = [
  {
    questions: "What is Your Product Quality?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "What is Your Product Quality?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "What Shipping Methods Are Available?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "What Payment Methods Are Accepted?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "How Do I Place an Order?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "How Do I Pay?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "Will the Vegetables Be Fresh?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
  {
    questions: "Can I Order Over Phone?",
    answer: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at diam leo. Mauris a ante placerat, dignissim orci eget, viverra ante. Mauris ornare pellentesque augue. Curabitur leo nibh, ultrices vel ultricies eu, vulputate at felis.`,
  },
];
export const recipsarticlesdata = [
  {
    img: "/assets/images/recips-img-1.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-10.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-2.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-3.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-4.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-5.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-1.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-6.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-7.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-8.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-9.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
  {
    img: "/assets/images/recips-img-10.png",
    category: "Category",
    time: "June 22, 2022",
    title: "We Always Ready to Give You Best Delivery Support",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    userImg: "/assets/images/recips-user-img-1.png",
    userName: "Darlene Robertson",
  },
];

export const whatweprovidecarddata = [
  {
    imageURL: "/assets/images/best-prices-and-offer.png",
    heading: "Best Prices & Offers",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
  {
    imageURL: "/assets/images/wide-assortment-img.png",
    heading: "Wide Assortment",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
  {
    imageURL: "/assets/images/free-delivery-img.png",
    heading: "Free Delivery",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
  {
    imageURL: "/assets/images/easy-returns-img.png",
    heading: "Easy Returns",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
  {
    imageURL: "/assets/images/100per-satisfaction.png",
    heading: "100% Satisfaction",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
  {
    imageURL: "/assets/images/great-daily-deal.png",
    heading: "Great Daily Deal",
    description: `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form`,
  },
];
export const ourteamdata = [
  {
    img: "/assets/images/team1.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team2.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team3.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team4.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team5.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team6.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team7.png",
    name: "Esther Howard",
    rank: "Manager",
  },
  {
    img: "/assets/images/team8.png",
    name: "Esther Howard",
    rank: "Manager",
  },
];

export const footerlinksdata = [
  { name: "Beans", link: "/beans" },
  { name: "Carrots", link: "/carrots" },
  { name: "Apples", link: "/apples" },
  { name: "Garlic", link: "/garlic" },
  { name: "Mushrooms", link: "/mushrooms" },
  { name: "Tomatoes", link: "/tomatoes" },
  { name: "Chilli peppers", link: "/chilli-peppers" },
  { name: "Broccoli", link: "/broccoli" },
  { name: "Watermelons", link: "/watermelons" },
  { name: "Cherries", link: "/cherries" },
  { name: "Meat", link: "/meat" },
  { name: "Seo tag", link: "/seo-tag" },
  { name: "Fish", link: "/fish" },
  { name: "Seo tag", link: "/seo-tag" },
  { name: "Fresh food", link: "/fresh-food" },
  { name: "Lemons", link: "/lemons" },
];
export const shopbycateogries = [];
